<div class="row">
<h1>
  <?php echo $this->titulo ?></h1>
</br>
<p>
Fecha:
<?php echo  $this->fecha ?></p>
</br>


<div class="span4">
<table>
  <tr>
    <td>
      <li>
        <?php echo $this->curso1 ?>
      </li>
    </td>
  </tr>
  <tr>
    <td>
      <li>
        <?php echo $this->curso2 ?>
      </li>
    </td>
  </tr>
  <tr>
    <td>
      <li>
        <?php echo $this->curso3 ?>
      </li>
    </td>
  </tr>
  <tr>
    <td>
      <li>
        <?php echo $this->curso4 ?>
      </li>
    </td>
  </tr>
</table>

</div>

</div>